# Travis CI (http://travis-ci.org/) is a continuous integration
# service for open source projects. This file configures it
# to run unit tests for github.com/mboersma/progress

language: go

go:
    - 1.2.1
    - tip

matrix:
    fast_finish: true

before_install:
    - go get -v code.google.com/p/go.tools/cmd/cover
    - go get -v code.google.com/p/go.tools/cmd/vet
    - go get -v golang.org/x/lint/golint
    - go get -v github.com/mattn/goveralls

script:
    - go vet -x ./...
    - $HOME/gopath/bin/golint .
    - go test -covermode=count -coverprofile=profile.cov -v .

after_script:
    - $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci
